# Generated by Django 3.0 on 2020-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20200424_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
